"use strict";
const $=id=>document.getElementById(id);
const token=new URLSearchParams(location.hash.slice(1)).get('token')||'';
history.replaceState(null,'',location.pathname);
let cursor=0,events=[],snapshot=null,selected=null,activeTab='activity',hiddenBefore=0,approvalSignature='',polling=false,bookmarkIds=new Set(),lastFocus=null;
const labels={action:'Approved action',exchange:'Agent exchange',user:'You',copilot:'Copilot',system:'System',warning:'Warning',error:'Error',status:'Status',plan:'Orchestrator',tool:'Tool',context:'Context',model:'Model',artifact:'Artifact',session:'Session',connection:'Connection'};
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,5000);$('live').textContent=text;}
async function api(path,body){const opts={headers:{Authorization:'Bearer '+token},cache:'no-store'};if(body!==undefined){opts.method='POST';opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(body);}const r=await fetch(path,opts);const v=await r.json();if(!r.ok)throw new Error(v.error||'Local request failed');return v;}
function details(title,value){const d=node('details');d.append(node('summary',title));d.append(node('pre',typeof value==='string'?value:JSON.stringify(value,null,2)));return d;}
function button(text,fn,cls){const b=node('button',text,cls);b.type='button';b.onclick=fn;return b;}
// Safe small Markdown subset: no raw HTML, remote images, executable links or scripts.
function inline(text,parent){const parts=String(text).split(/(`[^`]+`|\*\*[^*]+\*\*)/g);for(const part of parts){if(part.startsWith('`')&&part.endsWith('`'))parent.append(node('code',part.slice(1,-1)));else if(part.startsWith('**')&&part.endsWith('**'))parent.append(node('strong',part.slice(2,-2)));else parent.append(document.createTextNode(part));}}
function markdown(text){const box=node('div');const lines=String(text||'').split('\n');let i=0;while(i<lines.length){const line=lines[i];if(line.startsWith('```')){const language=line.slice(3).trim();const code=[];i++;while(i<lines.length&&!lines[i].startsWith('```'))code.push(lines[i++]);i++;const head=node('div',undefined,'code-head');head.append(node('span',language||'Code'));head.append(button('Copy',async()=>{try{await navigator.clipboard.writeText(code.join('\n'));toast('Code copied.');}catch{toast('Clipboard unavailable. Select and copy the code.');}}));box.append(head,node('pre',code.join('\n')));continue;}if(/^#{1,4} /.test(line)){const h=node('h3');inline(line.replace(/^#{1,4} /,''),h);box.append(h);i++;continue;}if(line.includes('|')&&i+1<lines.length&&/^\s*\|?\s*:?-{3}/.test(lines[i+1])){const table=node('table');const cells=s=>s.trim().replace(/^\||\|$/g,'').split('|').map(c=>c.trim());const head=node('thead'),row=node('tr');for(const cell of cells(line)){const th=node('th');th.scope='col';inline(cell,th);row.append(th);}head.append(row);table.append(head);i+=2;const body=node('tbody');while(i<lines.length&&lines[i].includes('|')){const tr=node('tr');for(const cell of cells(lines[i++])){const td=node('td');inline(cell,td);tr.append(td);}body.append(tr);}table.append(body);box.append(table);continue;}if(/^\s*[-*] /.test(line)){const ul=node('ul');while(i<lines.length&&/^\s*[-*] /.test(lines[i])){const li=node('li');inline(lines[i++].replace(/^\s*[-*] /,''),li);ul.append(li);}box.append(ul);continue;}if(line.trim()){const p=node('p');inline(line,p);box.append(p);}i++;}return box;}
function statusClass(status){if(['succeeded','complete','completed'].includes(status))return 'status-success';if(['failed','error'].includes(status))return 'status-error';if(['uncertain','awaiting_approval','blocked'].includes(status))return 'status-warning';return 'status-neutral';}
function statusRow(status){const row=node('div',undefined,'status-row '+statusClass(status));if(status==='running')row.append(node('span',undefined,'spinner'));row.append(node('span',String(status||'Not reported').replaceAll('_',' ')));return row;}
function selectEvent(e){selected=e;document.querySelectorAll('.message.selected').forEach(n=>n.classList.remove('selected'));$('event-'+e.id)?.classList.add('selected');renderInspector();}
function renderEvent(e){const p=e.payload;const article=node('article',undefined,'message '+e.kind+(e.kind==='exchange'?(p.actor==='Copilot'?' copilot':' system'):''));article.id='event-'+e.id;const head=node('div',undefined,'message-head');head.append(node('span',(labels[e.kind]||'Event').slice(0,1),'avatar'),node('strong',labels[e.kind]||'Event'));const time=node('time',new Date(e.time*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));time.dateTime=new Date(e.time*1000).toISOString();head.append(time,button('Inspect',()=>selectEvent(e)),button(bookmarkIds.has(e.id)?'Bookmarked':'Bookmark',()=>{bookmarkIds.has(e.id)?bookmarkIds.delete(e.id):bookmarkIds.add(e.id);renderBookmarks();renderMessages();}));article.append(head);const body=node('div',undefined,'message-body');if(e.kind==='exchange')body.append(node('strong',p.label||'Agent exchange'));if(e.kind==='tool'){body.append(node('strong',p.name||'Tool execution'),statusRow(p.status));if(typeof p.duration_ms==='number')body.append(node('p',(p.duration_ms/1000).toFixed(2)+' s','muted small'));body.append(markdown(p.summary||''));if(p.result!==undefined)body.append(details('Result details',p.result));}else if(e.kind==='plan'){body.append(node('strong',p.title||'Execution plan'));const list=node('ol',undefined,'steps');for(const [i,step] of (p.steps||[]).entries()){const li=node('li');li.append(node('span',step.step||i+1,'step-number'));const copy=node('div',undefined,'step-copy');copy.append(node('span',step.action||step.name||'Step'));if(step.verification)copy.append(node('small',step.verification));li.append(copy,statusRow(step.status||'pending'));list.append(li);}body.append(list);}else{body.append(markdown(p.text||p.summary||''));if(p.state)body.append(statusRow(p.state));}if(p.details)body.append(details('Details',p.details));if(e.kind==='artifact'){body.append(details('Artifact evidence',p));}article.append(body);return article;}
function renderMessages(){const thread=$('thread'),follow=thread.scrollHeight-thread.scrollTop-thread.clientHeight<90;const q=$('search').value.trim().toLowerCase();const fragment=document.createDocumentFragment();for(const e of events){if(e.id<=hiddenBefore)continue;if(q&&!JSON.stringify(e.payload).toLowerCase().includes(q))continue;fragment.append(renderEvent(e));}$('messages').replaceChildren(fragment);$('welcome').hidden=events.some(e=>e.id>hiddenBefore&&['user','copilot','plan','tool','exchange'].includes(e.kind));if(follow)thread.scrollTop=thread.scrollHeight;else $('jump').hidden=false;}
function renderBookmarks(){const box=$('bookmarks');box.replaceChildren();const list=events.filter(e=>bookmarkIds.has(e.id));if(!list.length){box.textContent='No bookmarks yet';return;}for(const e of list)box.append(button((e.payload.summary||e.payload.text||e.payload.name||labels[e.kind]).slice(0,50),()=>{$('event-'+e.id)?.scrollIntoView({block:'center'});selectEvent(e);},'nav'));}
function renderInspector(){const box=$('inspector-content');box.replaceChildren();if(activeTab==='activity'){box.append(node('h2','AGENT STATE'),node('div',snapshot?.busy?'Active turn':snapshot?.runtime_connected?'Ready':'Runtime not connected','inspector-card'));box.append(node('h2','EXECUTION HISTORY'));const tools=events.filter(e=>e.kind==='tool').slice(-40).reverse();if(!tools.length)box.append(node('p','No tools have run.','empty-small'));for(const e of tools){const b=button(e.payload.name||'Tool',()=>selectEvent(e),'tool-mini');b.append(node('span',(e.payload.status||'Not reported')+(typeof e.payload.duration_ms==='number'?' · '+(e.payload.duration_ms/1000).toFixed(2)+' s':'')));box.append(b);}box.append(node('h2','SELECTED EVENT'));box.append(selected?details(labels[selected.kind],selected.payload):node('p','Select a message or execution to inspect.','empty-small'));}else if(activeTab==='context'){box.append(node('h2','BACKEND CONTEXT'));const context=events.filter(e=>e.kind==='context').at(-1);box.append(context?details('Authoritative context',context.payload):node('p','No context has been supplied by a runtime.','empty-small'));box.append(node('h2','MEASURED PERFORMANCE'));const timed=events.filter(e=>e.kind==='tool'&&typeof e.payload.duration_ms==='number');box.append(node('p',timed.length?timed.length+' reported tool timings':'No timings reported.','empty-small'));box.append(node('p','Token usage: unavailable','empty-small'));}else{box.append(node('h2','SESSION'));const session=events.filter(e=>e.kind==='session').at(-1);box.append(session?details('Backend session',session.payload):node('p','No backend session is connected.','empty-small'));box.append(node('h2','SUPPORTED ACTIONS'),details('Runtime capabilities',snapshot?.capabilities||{}));box.append(node('p','UI state is not execution authority. Approvals and uncertainty remain backend-owned.','empty-small'));}}
function modal(title,content){lastFocus=document.activeElement;$('modal-title').textContent=title;$('modal-content').replaceChildren(content);if(!$('modal').open)$('modal').showModal();}
$('modal-close').onclick=()=>$('modal').close();$('modal').addEventListener('close',()=>lastFocus?.focus());
function approvalReview(item){const p=item.preview,box=node('div',undefined,'action-review');box.append(node('p','Review the complete immutable proposal. This decision does not approve changed code, targets, permissions or scope.'));box.append(node('pre',JSON.stringify(p,null,2)));const row=node('div',undefined,'dialog-actions');for(const [decision,label] of [['deny','Deny'],['once','Allow this execution once'],['plan','Allow this exact plan']]){row.append(button(label,async()=>{row.querySelectorAll('button').forEach(b=>b.disabled=true);try{await api('/api/approval',{ticket:item.ticket,decision,plan_hash:p.plan_hash,call_hash:p.call_hash});$('modal').close();toast('Decision sent to the backend: '+decision+'.');approvalSignature='';await poll();}catch(e){toast(e.message);row.querySelectorAll('button').forEach(b=>b.disabled=false);}},decision==='deny'?'':'primary'));}box.append(row);modal('Explicit approval required',box);}
function renderApprovals(items){const signature=JSON.stringify(items);if(signature===approvalSignature)return;approvalSignature=signature;const box=$('approval-region');box.replaceChildren();for(const item of items){const card=node('div',undefined,'approval');card.append(node('h3','Approval required'),node('p','Execution is paused. Review the exact plan, script, targets and permissions before deciding.'),button('Review complete proposal',()=>approvalReview(item),'review'));box.append(card);}$('live').textContent=items.length?'An action requires your explicit approval.':'';}
function updateState(s){snapshot=s;$('send').disabled=!s.runtime_connected||s.busy||!$('composer').value.trim();$('stop').hidden=!s.busy;$('stop').disabled=!s.capabilities.stop;$('attach').disabled=!s.capabilities.attach||s.busy;$('new-session').disabled=!s.capabilities.new_session||s.busy;$('connection').textContent=s.runtime_connected?'Runtime connected':'UI only';$('health').textContent=s.runtime_connected?'Local runtime connected':'Live execution disabled';$('state-label').textContent=s.approvals.length?'Awaiting approval':s.busy?'Active turn':s.runtime_connected?'Ready':'Workspace shell';$('runtime-note').textContent=s.runtime_connected?'Connected to the reviewed local runtime.':'The UI is running. Agent startup integration is not connected; no prompt or tool has been executed.';const model=events.filter(e=>e.kind==='model').at(-1);$('model').textContent=model?(model.payload.name||'Model')+' · '+(model.payload.verified?'Verified':'Not verified'):'Model not verified';const session=events.filter(e=>e.kind==='session').at(-1);if(session?.payload.title)$('session-title').textContent=session.payload.title;$('count').textContent=events.length+' retained UI events';renderApprovals(s.approvals);renderInspector();}
async function poll(){if(polling)return;polling=true;try{const s=await api('/api/state?after='+cursor);if(s.events.length){events.push(...s.events);events=events.slice(-5000);cursor=s.cursor;renderMessages();renderBookmarks();}updateState(s);}catch(e){$('connection').textContent='Disconnected';$('send').disabled=true;$('stop').disabled=true;$('health').textContent=e.message;renderApprovals([]);}finally{polling=false;}}
async function send(){const text=$('composer').value;if(!text.trim())return;$('send').disabled=true;try{await api('/api/submit',{text});$('composer').value='';await poll();}catch(e){toast(e.message);if(snapshot)updateState(snapshot);}}
$('send').onclick=send;$('composer').addEventListener('input',()=>{if(snapshot)updateState(snapshot);});
async function action(name,value){try{await api('/api/action',{action:name,value});await poll();}catch(e){toast(e.message);}}
$('stop').onclick=()=>{const box=node('div');box.append(node('p','Stop requests cancellation where supported. A submitted action may still complete; this does not roll back changes.'),button('Request stop',()=>{$('modal').close();action('stop');},'primary'));modal('Stop agent',box);};
$('new-session').onclick=()=>{const box=node('div');box.append(node('p','Start a new backend session. This is not a request to delete retained files.'),button('Start new session',()=>{$('modal').close();action('new_session');},'primary'));modal('New session',box);};
$('attach').onclick=()=>{const box=node('div');box.append(node('p','The runtime must provide a reviewed local file picker. This UI does not upload files directly.'));box.append(button('Open reviewed file picker',()=>{$('modal').close();action('attach');},'primary'));modal('Attach files',box);};
function toggleLeft(){const l=document.querySelector('.layout');if(innerWidth<=720)l.classList.toggle('mobile-left');else l.classList.toggle('left-hidden');}
function toggleRight(){const l=document.querySelector('.layout');if(innerWidth<=1100)l.classList.toggle('mobile-right');else l.classList.toggle('right-hidden');}
$('toggle-left').onclick=toggleLeft;$('toggle-right').onclick=toggleRight;
document.querySelectorAll('.template').forEach(b=>b.onclick=()=>{$('composer').value=b.dataset.template;$('composer').focus();if(snapshot)updateState(snapshot);});
$('templates').onclick=()=>{const box=node('div');document.querySelectorAll('#sidebar .template').forEach(b=>box.append(button(b.textContent,()=>{$('composer').value=b.dataset.template;$('modal').close();$('composer').focus();if(snapshot)updateState(snapshot);},'command')));modal('Prompt templates',box);};
$('search').oninput=renderMessages;$('jump').onclick=()=>{$('thread').scrollTop=$('thread').scrollHeight;$('jump').hidden=true;};
$('clear-view').onclick=()=>{hiddenBefore=cursor;renderMessages();toast('View cleared. Backend context and retained evidence are unchanged.');};
$('export').onclick=()=>{const box=node('div');box.append(node('p','Exports visible UI messages as JSON. Review for sensitive content before sharing. It is not a full backend session export.'));box.append(button('Download visible transcript',()=>{const data=events.filter(e=>e.id>hiddenBefore);const blob=new Blob([JSON.stringify({format:'workspace-ui-transcript-1',events:data},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=node('a');a.href=url;a.download='workspace-transcript.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('modal').close();},'primary'));modal('Export review',box);};
$('settings').onclick=()=>{const box=node('div');box.append(node('p','Display settings only. Runtime permissions and configuration are unchanged.'));box.append(button('Toggle compact density',()=>document.body.classList.toggle('compact'),'command'),node('p','The workspace uses an accessible light theme.'));modal('Workspace settings',box);};
$('notifications').onclick=()=>{const box=node('div');const items=events.filter(e=>['error','warning','status'].includes(e.kind)).slice(-15).reverse();if(!items.length)box.append(node('p','No notifications.'));for(const e of items)box.append(button(e.payload.summary||e.payload.state||labels[e.kind],()=>{$('modal').close();selectEvent(e);$('event-'+e.id)?.scrollIntoView({block:'center'});},'command'));modal('Recent activity',box);};
$('debug').onclick=()=>{const box=node('div');box.append(node('p','UI connection diagnostics. Backend raw logs and private reasoning are not collected here.'),details('Connection state',{connected:snapshot?.runtime_connected||false,busy:snapshot?.busy||false,cursor,retained_events:events.length,capabilities:snapshot?.capabilities||{}}));modal('Diagnostics',box);};
function palette(){const box=node('div'),input=node('input');input.placeholder='Find a command…';input.setAttribute('aria-label','Search commands');box.append(input);const commands=[['Focus composer',()=>$('composer').focus()],['Search messages',()=>$('search').focus()],['Toggle sessions',toggleLeft],['Toggle inspector',toggleRight],['Export visible transcript',()=>$('export').click()],['Display settings',()=>$('settings').click()],['Restore cleared view',()=>{hiddenBefore=0;renderMessages();}]];const list=node('div');box.append(list);function filter(){list.replaceChildren();for(const [label,fn] of commands)if(label.toLowerCase().includes(input.value.toLowerCase()))list.append(button(label,()=>{$('modal').close();fn();},'command'));}input.oninput=filter;filter();modal('Command palette',box);input.focus();}
$('palette-button').onclick=palette;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(t=>t.setAttribute('aria-selected',String(t===b)));renderInspector();});
document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='Enter'&&!$('modal').open){e.preventDefault();if(!$('send').disabled)send();}if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();palette();}if(e.ctrlKey&&e.key.toLowerCase()==='b'){e.preventDefault();toggleLeft();}if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='f'){e.preventDefault();$('search').focus();}});
if(!token){$('runtime-note').textContent='Launch this workspace using workspace.py to obtain a local authenticated connection.';$('connection').textContent='No launch token';}else{poll();setInterval(poll,900);}

// Focused layout: no automatic theme switching, no added execution capability.
document.body.classList.add('light');
const focusedComposer=document.getElementById('composer');
function fitComposer(){focusedComposer.style.height='auto';const cap=Math.min(innerHeight*.38,360);const size=Math.min(Math.max(focusedComposer.scrollHeight,52),cap);focusedComposer.style.height=size+'px';focusedComposer.style.overflowY=focusedComposer.scrollHeight>cap?'auto':'hidden';}
focusedComposer.addEventListener('input',fitComposer);
window.addEventListener('resize',fitComposer);
const attachmentContainer=document.getElementById('attachments');
if(attachmentContainer)new MutationObserver(fitComposer).observe(attachmentContainer,{childList:true,subtree:true});
document.getElementById('focus-export').onclick=()=>document.getElementById('export').click();
fitComposer();

async function permissionManager(){try{const data=await api('/api/permissions');const box=node('div');box.append(node('p','Durable research permissions never authorise writes, downloads or exports. Those require separate exact approval.'));for(const grant of data.grants){const card=node('section',undefined,'permission-card');card.append(node('h3',grant.purpose),node('p',Object.values(grant.scope).join(' ? ')),node('p','State: '+grant.state+' ? '+grant.expiry_mode),node('p',grant.capabilities.join(', ')),details('Limits and identity checks',{limits:grant.limits,identity_checks:grant.identity_checks,created_at:grant.created_at,last_use:grant.last_use,expires_at:grant.expires_at}));const change=async(action,changes)=>{try{$('modal').close();await api('/api/permissions/manage',{action,grant_id:grant.grant_id,changes});toast('Permission '+action+' completed.');}catch(e){toast(e.message);}};card.append(button('Pause',()=>change('pause')),button('Revoke',()=>change('revoke')),button('Renew',()=>change('renew')),button('Edit',()=>{const form=node('div');const purpose=node('input');purpose.value=grant.purpose;form.append(node('label','Research purpose'),purpose);const choices=[];for(const cap of data.capabilities){const label=node('label',undefined,'permission-choice'),input=node('input');input.type='checkbox';input.checked=grant.capabilities.includes(cap);choices.push([cap,input]);label.append(input,document.createTextNode(cap));form.append(label);}const limits=node('textarea');limits.value=JSON.stringify(grant.limits,null,2);limits.rows=14;form.append(node('label','Operational limits'),limits);const expiry=node('input');expiry.type='number';expiry.min=1;expiry.max=365;expiry.value=grant.expiry_days||'';form.append(node('label','Expiry in days (blank means until revoked)'),expiry,button('Review changes',()=>{try{const changes={purpose:purpose.value,capabilities:choices.filter(x=>x[1].checked).map(x=>x[0]),limits:JSON.parse(limits.value),expiry_days:expiry.value?Number(expiry.value):null};change('edit',changes);}catch(e){toast('Enter valid limits: '+e.message);}},'primary'));modal('Edit research permission',form);}));box.append(card);}if(!data.grants.length)box.append(node('p','No research grants. Ask Copilot to propose scoped research permission.'));modal('Research permissions',box);}catch(e){toast(e.message);}}
const permissionButton=button('Research permissions',permissionManager,'command');$('settings').parentElement.append(permissionButton);
